### ISSUE TITLE
Colors are broken on MacOS

### ISSUE THREAD

**Issue by nitrogenfive** [SkyDeckAGoGo/bta-issues#196] opened 2022-07-31 23:19 UTC
Version: `1.7.6.2_02`
Description: Colors appear to be off running the game on MacOS
Additional Info: [link to latest.log](https://mclo.gs/KtHadbE)
<img width="966" alt="Screen Shot 2022-08-01 at 7 08 17 am" src="https://user-images.githubusercontent.com/105533515/182049347-93f6250f-405d-4a29-8b27-ac90fcc876b8.png">
<img width="966" alt="Screen Shot 2022-08-01 at 7 07 02 am" src="https://user-images.githubusercontent.com/105533515/182049365-60235552-681e-427a-afa8-4ec3224f5005.png">
<img width="966" alt="Screen Shot 2022-08-01 at 7 09 07 am" src="https://user-images.githubusercontent.com/105533515/182049368-c35a35e7-fd95-4bd5-9237-89b4c36fc8d2.png">

**Comment by Joe4422** [comment] 2022-07-31 23:20
Duplicate of #194.

**Closed by Joe4422** 2022-07-31 23:20 UTC
Labels: Bug
